### ISSUE TITLE
Problem in installing "https://github.com/flare9x/FitnessForService.jl"

### ISSUE THREAD

**Issue by matrixbot123** [flare9x/FitnessForService.jl#3]
<img width="887" alt="error_julia" src="https://user-images.githubusercontent.com/32158555/103680137-bafbd400-4fab-11eb-857a-ae94fec5fdb7.PNG">

**Comment by flare9x** [comment]
May you please try again. I updated Project.toml

**Comment by matrixbot123** [comment]
The problem was resolved after the project.toml file was updated.
